# Generated by Django 5.2.4 on 2025-08-04 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tailwind', 'Tailwind'), ('bootstrap', 'Bootstrap')], max_length=50)),
                ('component_type', models.CharField(choices=[('layout', 'Layout'), ('navigation', 'Navigation'), ('forms', 'Forms'), ('buttons', 'Buttons'), ('feedback', 'Feedback'), ('data_display', 'Data Display'), ('special', 'Special')], max_length=100)),
                ('component_name', models.CharField(max_length=100)),
                ('class_names', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'platform', 'component_type', 'component_name')},
            },
        ),
    ]
