# Generated by Django 5.2.4 on 2025-08-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_styleconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleconfig',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
